# Prefix to C-t
set-option -g prefix C-t
unbind-key C-b
bind C-t send-prefix

# color pallet
color_bg=colour232
color_inactive=colour234
color_sub=colour236
color_key=colour241
color_text=colour255

# basics
set -g terminal-overrides 'xterm*:smcup@:rmcup@'
set -g default-terminal "xterm-256color"
set-option -gw xterm-keys on
set -g mouse on
set -g history-limit 20000
set -sg escape-time 0
set -g base-index 1

# status bar
set -g status on
set -g status-interval 2
set -g status-position top
set -g status-justify "left"
set -g status-left ""
status_right_format="#h [#S]"
set -g status-right "$status_right_format"
set-option -g status-right-length 50
## color
set -g status-style "bg=$color_bg,fg=$color_key"

# basic key binds
unbind C-r
bind C-r source-file ~/.tmux.conf\; display-message "$HOME/.tmux.conf reloaded!"

unbind C-p
bind C-p \
  if-shell -F '#{==:#{pane_index},1}' \
  'previous-window; run "tmux select-pane -t $(tmux list-panes | wc -l)"' \
  'select-pane -t :.-'
unbind C-n
bind C-n \
  if-shell -F '#{==:#{pane_index},#{window_panes}}' \
  'next-window; select-pane -t 1' \
  'select-pane -t :.+'

unbind -n M-Left
bind -n M-Left select-pane -L
unbind -n M-Right
bind -n M-Right select-pane -R
unbind -n M-Up
bind -n M-Up select-pane -U
unbind -n M-Down
bind -n M-Down select-pane -D

unbind -n M-h
bind -n M-h select-pane -L
unbind -n M-j
bind -n M-j select-pane -D
unbind -n M-k
bind -n M-k select-pane -U
unbind -n M-l
bind -n M-l select-pane -R

unbind -n C-Pageup
bind -n C-Pageup \
  if-shell -F '#{==:#{pane_index},1}' \
  'previous-window; run "tmux select-pane -t $(tmux list-panes | wc -l)"' \
  'select-pane -t :.-'
unbind -n C-Pagedown
bind -n C-Pagedown \
  if-shell -F '#{==:#{pane_index},#{window_panes}}' \
  'next-window; select-pane -t 1' \
  'select-pane -t :.+'

# window
unbind -n C-n
bind -n C-n new-window -a -c "#{pane_current_path}"
unbind -n C-w
bind -n C-w kill-pane
setw -g pane-base-index 1
setw -g window-status-style "bg=$color_sub"
setw -g window-status-format "     "
setw -g window-status-current-style "bg=$color_key"
setw -g window-status-current-format "     "

# pane
unbind -n M-¥
bind -n M-¥ split-window -h -c "#{pane_current_path}"
unbind -n M--
bind -n M-- split-window -v -c "#{pane_current_path}"
unbind -n C-h
bind -n C-h split-window -h -c "#{pane_current_path}"
unbind -n C-v
bind -n C-v split-window -v -c "#{pane_current_path}"
set -g pane-border-style "fg=$color_key"
set -g pane-active-border-style "fg=$color_text"

# copy mode
bind -T copy-mode u send-keys -X page-up
bind -T copy-mode d send-keys -X page-down
bind -T copy-mode Enter send-keys -X cancel

# off mode
bind -T root F12 \
  set prefix None\; \
  set key-table off\; \
  set status-style "fg=$color_sub"\; \
  setw -g window-status-style "bg=$color_inactive"\; \
  setw window-status-current-style "bg=$color_sub"\; \
  refresh-client -S
bind -T off F12 \
  set -u prefix\; \
  set -u key-table\; \
  set -u status-style\; \
  setw -g window-status-style "bg=$color_sub"\; \
  setw -u window-status-current-style\; \
  refresh-client -S
